title: lithedream
description: software, agents, precision, resonance
markdown: kramdown
theme: minima
show_excerpts: false
github_username: lithedream
linkedin_username: luca-amadori-codepunk
header_pages:
  - index.md
  - /about/index.md
  - /projects/index.md
  - /guides/index.md
collections:
  projects:
    output: true
    permalink: /projects/:name/
  guides:
    output: true
    permalink: /guides/:name/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "guides"
    values:
      layout: page