title: lithedream
description: software, agents, precision, resonance
markdown: kramdown
theme: minima
show_excerpts: false
collections:
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page